name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up containers
        run: ./build.sh && ./run.sh

      - name: Run tests depending only on local network
        run: docker exec github-action-revel sh -c 'revel test myapp dev'
